# Generated by Django 5.1.6 on 2025-02-27 15:12

import apps.newspaper.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Newspaper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "publisher",
                    models.CharField(max_length=100, verbose_name="Publisher"),
                ),
                ("publication_date", models.DateField(verbose_name="Publication Date")),
                ("language", models.CharField(max_length=50, verbose_name="Language")),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("news", "Noticias"),
                            ("sports", "Deportes"),
                            ("technology", "Tecnología"),
                            ("entertainment", "Entretenimiento"),
                            ("other", "Otro"),
                        ],
                        default="news",
                        max_length=20,
                        verbose_name="Genre",
                    ),
                ),
                (
                    "edition",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Edition"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.newspaper.models.newspaper_cover_path,
                        verbose_name="Cover Image",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Disponible"),
                            ("borrowed", "Prestado"),
                            ("under_repair", "En Reparación"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "physical_location",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Physical Location",
                    ),
                ),
                (
                    "issn",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="ISSN",
                    ),
                ),
                (
                    "pages",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Pages"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Price",
                    ),
                ),
            ],
            options={
                "verbose_name": "Newspaper",
                "verbose_name_plural": "Newspapers",
            },
        ),
    ]
