# Generated by Django 5.1.6 on 2025-03-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newspaper", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newspaper",
            name="scope",
            field=models.CharField(
                choices=[
                    ("nacional", "Nacional"),
                    ("provincial", "Provincial"),
                    ("regional", "Regional"),
                ],
                default="nacional",
                max_length=20,
                verbose_name="Alcance",
            ),
        ),
        migrations.AlterField(
            model_name="newspaper",
            name="genre",
            field=models.CharField(
                choices=[
                    ("noticias", "Noticias"),
                    ("deportes", "Deportes"),
                    ("tecnologia", "Tecnología"),
                    ("entretenimiento", "Entretenimiento"),
                    ("politica", "Política"),
                    ("cultura", "Cultura"),
                    ("otros", "Otros"),
                ],
                default="noticias",
                max_length=20,
                verbose_name="Género",
            ),
        ),
    ]
