# Generated by Django 5.1.7 on 2025-03-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newspaper", "0002_newspaper_scope_alter_newspaper_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="newspaper",
            name="copete",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Copete"
            ),
        ),
    ]
