# Generated by Django 5.1.6 on 2025-03-10 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("newspaper", "0002_newspaper_scope_alter_newspaper_genre"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cardex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "circulation",
                    models.PositiveIntegerField(verbose_name="Circulación"),
                ),
                (
                    "issue_number",
                    models.CharField(max_length=50, verbose_name="Número de Edición"),
                ),
                (
                    "content_summary",
                    models.TextField(verbose_name="Resumen de Contenido"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "newspaper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cardex_entries",
                        to="newspaper.newspaper",
                        verbose_name="Periódico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ficha Cardex",
                "verbose_name_plural": "Fichas Cardex",
            },
        ),
    ]
