# Generated by Django 5.1.6 on 2025-03-10 13:48

import apps.cardex.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardex", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardex",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to=apps.cardex.models.cardex_file_path
            ),
        ),
    ]
